### ISSUE TITLE
EntranceSituation1E.java "feature"

### ISSUE THREAD

**Issue by Archnitest** [hangilk/TextAdventure#4] opened 2023-02-21 20:36 UTC
Just wanted to let you know that the current code allows you to spam the "non-bedroom" buttons which floods the textpanel with the dialogue result, but it reaches a limit where it doesn't display any more as it reaches the bottom of the screen.

One possible solution is capping the buttons or clearing the screen before doing anything else as a button is pressed.

**Comment by 82hk** [comment] 2023-02-21 20:38
The current implementation of the text panel makes it so that it can't be scrollable, which means that as Derek stated the panel needs to be cleared (or any other implementation)

**Comment by doodleasa** [comment] 2023-02-21 21:03
That sounds like an issue that should probably be fixed with the UI. I'm sure we're going to want that functionality at some point, for long conversations or w/e

**Comment by 82hk** [comment] 2023-02-21 21:33
The issue is the dialogue should never be that long, realistically. Any longer than the current space we have I see as unnecessary. However, if we do run into issues with text length, I'll see what I can do.
For now, any optimizations should be done within the writing itself, rather than the UI, or else we abandon text wrapping within the list's entries (which is arguably more important)

**Closed as completed** 2023-03-03 21:31 UTC
Labels: bug
